// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjktvhbcerugvaixavuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhqa3R2aGJjZXJ1Z3ZhaXhhdnVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMTA3MTUsImV4cCI6MjA3MDY4NjcxNX0.MIIDFovR9uidFJ-elyCPzl4cWdrjaqVspj0wIXFS2YA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});